Feature/local-storage-add
OlgaGav/what-am-i-craving-today pull request #37
Opened 2022-10-31 21:39 UTC by junnel308

this PR added:

- changed menu bar style and animation through materialized
- fixed a bug where button and text are overlapping the menu bar
- function to store to local storage and no duplicated
- changed local storage bar style and animation through materialized
- fix bug where mutiple URL will open when "See Yelp Reviews" is clicked each time.

2022-10-31 23:06 UTC, OlgaGav requested changes
JP, could you please review my comments. They are failing the script. Empty space I suppose is just typo but they should be fixed.

2022-11-01 02:10 UTC, D0KD0 approved these changes

2022-11-01 02:10 UTC, layesicaa approved these changes

2022-11-01 02:23 UTC, OlgaGav approved these changes

2022-11-01 02:24 UTC, merged